/* The published result of the 校外（external visitor）viewing draw.
 *
 * The dataset is generated by scripts/build-lottery-results.mjs from the
 * private 2026-lottery repo's out/external-results.csv and committed as
 * content/lottery/results.json — applicant names and e-mail addresses are
 * stripped there, so nothing but the pseudonymous 抽選番号 ever lands in this
 * public repository. Never hand-edit the JSON; regenerate it instead. */

import results from "@/content/lottery/results.json";

export type Performance = {
  /** ASCII, stable across regenerations: "0912-1-5A". */
  readonly id: string;
  /** "0912" — sorts chronologically as a string. */
  readonly date: string;
  readonly dateLabel: string;
  readonly stageNumber: number;
  readonly stageLabel: string;
  readonly timeLabel: string;
  readonly classId: string;
  readonly classLabel: string;
};

export type LotteryStatus = "won" | "excluded";

export type LotteryEntry = {
  readonly number: string;
  readonly status: LotteryStatus;
  /** Null for 対象外 entries, which never reached the draw. */
  readonly partySize: number | null;
  /** Performance ids, in the order they were drawn. */
  readonly wins: readonly string[];
  /** Why an entry was excluded; empty for everyone else. */
  readonly note: string;
};

export const PERFORMANCES = results.performances as readonly Performance[];

export const ENTRIES = results.entries.map((entry) => ({
  ...entry,
  status: entry.status as LotteryStatus,
})) as readonly LotteryEntry[];

const PERFORMANCE_BY_ID = new Map(
  PERFORMANCES.map((performance) => [performance.id, performance]),
);

const ENTRY_BY_NUMBER = new Map(ENTRIES.map((entry) => [entry.number, entry]));

/** How many digits a LoGo フォーム 受付番号 carries (AE + 8 digits). */
const RECEIPT_DIGITS = 8;
const LOTTERY_DIGITS = 4;

/**
 * Accepts what a visitor actually has to hand — the 4-digit 抽選番号, the same
 * number without its leading zeros, or the whole 受付番号 off their
 * confirmation mail ("AE00046805") — and returns the canonical 4-digit form.
 *
 * The 抽選番号 is the 受付番号 with its last two digits removed, so anything
 * long enough to be a 受付番号 gets those two dropped before the last four
 * digits are taken. Full-width digits are folded first: a Japanese IME left in
 * 全角 is the most likely way to mistype this field.
 *
 * Returns null when the input holds no digits at all.
 */
export function normalizeLotteryNumber(input: string): string | null {
  const digits = input
    .replace(/[０-９]/g, (char) =>
      String.fromCharCode(char.charCodeAt(0) - 0xfee0),
    )
    .replace(/\D/g, "");

  if (digits.length === 0) return null;

  const trimmed =
    digits.length >= RECEIPT_DIGITS - 2 ? digits.slice(0, -2) : digits;

  return trimmed.slice(-LOTTERY_DIGITS).padStart(LOTTERY_DIGITS, "0");
}

export function findLotteryEntry(number: string): LotteryEntry | null {
  return ENTRY_BY_NUMBER.get(number) ?? null;
}

export function performanceById(id: string): Performance {
  const performance = PERFORMANCE_BY_ID.get(id);
  if (!performance) {
    throw new Error(`No performance registered for id "${id}".`);
  }
  return performance;
}

export type PerformanceListing = {
  readonly performance: Performance;
  /** Winning 抽選番号, ascending. */
  readonly numbers: readonly string[];
};

export type StageListing = {
  readonly key: string;
  readonly stageLabel: string;
  readonly timeLabel: string;
  readonly classes: readonly PerformanceListing[];
};

export type DayListing = {
  readonly date: string;
  readonly dateLabel: string;
  readonly stages: readonly StageListing[];
};

/**
 * Regroups the flat entry list into the day → 公演 → クラス shape the page
 * renders. PERFORMANCES is already sorted that way by the generator, so this
 * only has to walk it once and keep the first-seen order.
 */
export function buildDayListings(): readonly DayListing[] {
  const numbersByPerformance = new Map<string, string[]>();
  for (const entry of ENTRIES) {
    for (const id of entry.wins) {
      const bucket = numbersByPerformance.get(id);
      if (bucket) {
        bucket.push(entry.number);
      } else {
        numbersByPerformance.set(id, [entry.number]);
      }
    }
  }

  type StageDraft = {
    key: string;
    stageLabel: string;
    timeLabel: string;
    classes: PerformanceListing[];
  };
  type DayDraft = {
    date: string;
    dateLabel: string;
    stages: StageDraft[];
  };

  const days: DayDraft[] = [];
  const dayByDate = new Map<string, DayDraft>();
  const stageByKey = new Map<string, StageDraft>();

  for (const performance of PERFORMANCES) {
    let day = dayByDate.get(performance.date);
    if (!day) {
      day = {
        date: performance.date,
        dateLabel: performance.dateLabel,
        stages: [],
      };
      dayByDate.set(performance.date, day);
      days.push(day);
    }

    const stageKey = `${performance.date}-${performance.stageNumber}`;
    let stage = stageByKey.get(stageKey);
    if (!stage) {
      stage = {
        key: stageKey,
        stageLabel: performance.stageLabel,
        timeLabel: performance.timeLabel,
        classes: [],
      };
      stageByKey.set(stageKey, stage);
      day.stages.push(stage);
    }

    stage.classes.push({
      performance,
      numbers: (numbersByPerformance.get(performance.id) ?? []).sort((a, b) =>
        a.localeCompare(b),
      ),
    });
  }

  return days;
}

export const WINNER_COUNT = ENTRIES.filter(
  (entry) => entry.status === "won",
).length;

export const EXCLUDED_COUNT = ENTRIES.length - WINNER_COUNT;

export const SEAT_COUNT = ENTRIES.reduce(
  (total, entry) => total + entry.wins.length * (entry.partySize ?? 0),
  0,
);
